// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-categories.ts
import { createClient } from "npm:@supabase/supabase-js@^2.102.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_categories_default = defineTool({
  name: "list_categories",
  title: "List categories with tools",
  description: "Returns every Mentatools category with its nested tools, ordered by sort_order.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data: categories, error: cErr } = await sb.from("categories").select("*").order("sort_order");
    if (cErr) return { content: [{ type: "text", text: cErr.message }], isError: true };
    const { data: tools, error: tErr } = await sb.from("tools").select("*").order("sort_order");
    if (tErr) return { content: [{ type: "text", text: tErr.message }], isError: true };
    const result = (categories ?? []).map((c) => ({
      ...c,
      tools: (tools ?? []).filter((t) => t.category_id === c.id)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { categories: result }
    };
  }
});

// src/lib/mcp/tools/create-category.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.102.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_category_default = defineTool2({
  name: "create_category",
  title: "Create a category",
  description: "Insert a new category. Requires admin role \u2014 RLS rejects the call otherwise.",
  inputSchema: {
    title: z.string().trim().min(1),
    sort_order: z.number().int().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("categories").insert(input).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { category: data }
    };
  }
});

// src/lib/mcp/tools/create-tool.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.102.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_tool_default = defineTool3({
  name: "create_tool",
  title: "Create a tool",
  description: "Insert a new tool row inside an existing category. Requires admin role \u2014 RLS rejects the call otherwise.",
  inputSchema: {
    category_id: z2.string().uuid().describe("UUID of the parent category."),
    name: z2.string().trim().min(1),
    url: z2.string().url(),
    description: z2.string().trim().min(1),
    sort_order: z2.number().int().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("tools").insert(input).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { tool: data }
    };
  }
});

// src/lib/mcp/tools/delete-tool.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.102.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var delete_tool_default = defineTool4({
  name: "delete_tool",
  title: "Delete a tool",
  description: "Delete a tool row by id. Requires admin role \u2014 RLS rejects the call otherwise.",
  inputSchema: { id: z3.string().uuid() },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { error } = await supabaseForUser4(ctx).from("tools").delete().eq("id", id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Deleted ${id}` }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bxokofbkarrlwncbpaoz";
var mcp_default = defineMcp({
  name: "mentatools-mcp",
  title: "Mentatools MCP",
  version: "0.1.0",
  instructions: "Tools for the Mentatools directory. Use `list_categories` to browse the catalog. Admin users can also create categories, create tools, and delete tools.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_categories_default, create_category_default, create_tool_default, delete_tool_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
